### ISSUE TITLE
Missing August Summer bank holiday (not a duplicate)

### ISSUE THREAD

**Issue by lukemarshhb** [ministryofjustice/govuk-bank-holidays#20]
The summer bank holiday 28th August is not being returned. I have supplied a division and also tried without buy no luck. Please can you help?

**Comment by ushkarev** [comment]
This library loads bank holiday info from GOV.UK by default (https://www.gov.uk/bank-holidays.json) though there is a cached (and possibly outdated) version packaged here. If the source data set is wrong, then we can’t really do anything about that of course.

It looks like this particular holiday varies across the "divisions" (as GOV.UK call it) of the UK – it’s on the 7th in Scotland. So if you don’t supply a "division", the library only serves dates that are common to _all_ divisions.

Try this…

```python
import datetime
from govuk_bank_holidays.bank_holidays import BankHolidays

bank_holidays = BankHolidays()
# looking forward from August…
next_holiday_across_all_division = bank_holidays.get_next_holiday(date=datetime.date(2023, 8, 1))
next_holiday_in_scotland = bank_holidays.get_next_holiday(date=datetime.date(2023, 8, 1), division=BankHolidays.SCOTLAND)
next_holiday_in_england_and_wales = bank_holidays.get_next_holiday(date=datetime.date(2023, 8, 1), division=BankHolidays.ENGLAND_AND_WALES)
```

`next_holiday_across_all_division` is Christmas! `next_holiday_in_scotland` is 7 August but `next_holiday_in_england_and_wales` is 28 August.

**Comment by lukemarshhb** [comment]
@ushkarev Thanks for your response. I've checked the json file and the summer bank holiday is in there but its not being returned when I run this:

```
bank_holidays = BankHolidays(BankHolidays.ENGLAND_AND_WALES)
```

**Comment by ushkarev** [comment]
The problem is that you’re passing the division into the wrong method.

`BankHolidays(BankHolidays.ENGLAND_AND_WALES)` is incorrect because the [initialisation method](https://github.com/ministryofjustice/govuk-bank-holidays/blob/5b7361fc3a6a07489c397ebc6434a1107e44cf57/govuk_bank_holidays/bank_holidays.py#L35) does not accept a division argument. Have a look at the other methods on the class that actually return bank holidays – they’re the ones that accept a division argument. For example the `get_next_holiday` I used in my sample snippet.

**Comment by lukemarshhb** [comment]
Thank you!!
